name: mvp-agibank
services:
  ms-customer-api:
    image: ms-customer:latest
    build: ./ms-customer
    networks:
      - mvp-agibank-network
    ports:
      - "8080:8080"
    depends_on:
      - customer-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://customer-db:5432/ms-customer-db?createDatabaseIfNotExist=true?useSSL=false?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  customer-db:
    image: postgres:latest
    container_name: postgres_customer
    environment:
      POSTGRES_DB: ms-customer-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    networks:
      - mvp-agibank-network

  ###################################################################################################################
  ms-insurance-api:
    image: ms-insurance:latest
    build: ./ms-insurance
    networks:
      - mvp-agibank-network
    ports:
      - "8081:8081"
    depends_on:
      - insurance-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://insurance-db:5432/ms-insurance-db?createDatabaseIfNotExist=true?useSSL=false?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MS_CUSTOMER_HOST: ms-customer-api:8080

  insurance-db:
    image: postgres:latest
    container_name: postgres_insurance
    environment:
      POSTGRES_DB: ms-insurance-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
    networks:
      - mvp-agibank-network

  ###################################################################################################################
networks:
  mvp-agibank-network:
    driver: bridge