services:
  ms-customer-api:
    image: ms-customer:latest
    build: ./ms-customer
    networks:
      - mvp-agibank-network
    ports:
      - "8080:8080"
    depends_on:
      - ms-customer-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ms-customer-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  ms-customer-db:
    image: postgres:latest
    container_name: postgres_customer
    environment:
      POSTGRES_DB: ms-customer-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5419:5432"
    networks:
      - mvp-agibank-network

  ###################################################################################################################
  ms-insurance-api:
    image: ms-insurance:latest
    build: ./ms-insurance
    networks:
      - mvp-agibank-network
    ports:
      - "8081:8081"
    depends_on:
      - ms-insurance-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ms-insurance-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  ms-insurance-db:
    image: postgres:latest
    container_name: postgres_insurance
    environment:
      POSTGRES_DB: ms-insurance-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5420:5432"
    networks:
      - mvp-agibank-network

  ###################################################################################################################
networks:
  mvp-agibank-network:
    driver: bridge