spring:
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: ms-insurance

client-service:
    url: http://localhost:8080/api/v1

resilience4j:
  circuitbreaker:
    instances:
      simulaSeguro:
        registerHealthIndicator: true
        failureRateThreshold: 50 # % de falhas para abrir o circuit breaker
        slidingWindowSize: 2 # Número de chamadas para avaliar a falha
        waitDurationInOpenState: 5s # Tempo para aguardar antes de tentar novamente
        permittedNumberOfCallsInHalfOpenState: 3 # Número de chamadas permitidas no estado semi-aberto
      criaSeguro:
        registerHealthIndicator: true
        failureRateThreshold: 50 # % de falhas para abrir o circuit breaker
        slidingWindowSize: 2 # Número de chamadas para avaliar a falha
        waitDurationInOpenState: 5s # Tempo para aguardar antes de tentar novamente
        permittedNumberOfCallsInHalfOpenState: 3 # Número de chamadas permitidas no estado semi-aberto