spring:
  datasource:
    url: jdbc:h2:mem:ms-insurance-db
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  application:
    name: ms-customer
server:
  port: 8081
logging:
  level:
    org.modelmapper: DEBUG
client-service:
    url: http://localhost:8080/api/v1

resilience4j:
  circuitbreaker:
    instances:
      simulaSeguro:
        registerHealthIndicator: true
        failureRateThreshold: 50 # % de falhas para abrir o circuit breaker
        slidingWindowSize: 2 # Número de chamadas para avaliar a falha
        waitDurationInOpenState: 5s # Tempo para aguardar antes de tentar novamente
        permittedNumberOfCallsInHalfOpenState: 3 # Número de chamadas permitidas no estado semi-aberto
      criaSeguro:
        registerHealthIndicator: true
        failureRateThreshold: 50 # % de falhas para abrir o circuit breaker
        slidingWindowSize: 2 # Número de chamadas para avaliar a falha
        waitDurationInOpenState: 5s # Tempo para aguardar antes de tentar novamente
        permittedNumberOfCallsInHalfOpenState: 3 # Número de chamadas permitidas no estado semi-aberto