services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ms-insurance-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - ms-insurance-network
  ms-insurance:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ms-insurance-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - ms-insurance-network
networks:
  ms-insurance-network:
    driver: bridge